//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_JODBE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserManagementDBEntities : DbContext
    {
        public UserManagementDBEntities()
            : base("name=UserManagementDBEntities")
        {
            this.Database.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<ExcelImportLog> ExcelImportLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
